name: Test Action

on:
  push:
    branches:
      - main  # Change this if you want to trigger on a different branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: echo "23f1001716@ds.study.iitm.ac.in"
